spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/Ankitraj03711/Nexturn-config-repo.git
spring.cloud.config.server.git.default-label=main

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/microboot?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
